### ISSUE TITLE
Error Block refer to bad parent

### ISSUE THREAD

**Issue by fredbellard** [SilentNotaryEcosystem/Cil-core#31]
Hi team!
I'm running a node for a few weeks, and had issues that require to complety reinstall the node (delete the container and create it from scratch, sync, etc..).
I'm not the only one with similar issues, we've been discussing that in the telegram group for masternode support.
I'm facing this error again today, here are the first lines of the log:

2021-04-09T06:55:00.370490350Z [ 'Block 6784220cfa430af890c7a0b642a2db865f4a7471166e77da3379bc69f368fa5a. ConciliumId: 0. With 1 TXns and parents 0096b379cca507255e37b8bd9079fbc0112778c34bcf9a216dc4484ce8116ce5 was accepted' ]
2021-04-09T06:55:39.297127329Z [ 'connect ETIMEDOUT 3.17.139.84:8223' ]
2021-04-09T06:55:39.418784557Z [ 'connect ECONNREFUSED 3.17.181.53:8223' ]
2021-04-09T06:55:39.443715760Z [ 'connect ECONNREFUSED 146.59.12.211:8223' ]
2021-04-09T06:56:01.175203691Z [ 'Blocks 0096b379cca507255e37b8bd9079fbc0112778c34bcf9a216dc4484ce8116ce5 are stable now' ]
2021-04-09T06:56:01.222489392Z [ 'Block 3056f078b3262c643bd1831e06aee95d87b5ada7b2001a284d799487d2634eeb. ConciliumId: 4. With 1 TXns and parents 6784220cfa430af890c7a0b642a2db865f4a7471166e77da3379bc69f368fa5a was accepted' ]
2021-04-09T06:56:55.503809749Z [ 'Blocks 6784220cfa430af890c7a0b642a2db865f4a7471166e77da3379bc69f368fa5a are stable now' ]
2021-04-09T06:56:55.669584351Z [ 'Failed to execute "d7a242e4a05075f30c92a78a1e75f6916ce6b4490d64665d1a9ff8ee456a3d76"',
2021-04-09T06:56:55.669603678Z   'Already exist' ]
2021-04-09T06:56:55.681724739Z [ 'Block d7a242e4a05075f30c92a78a1e75f6916ce6b4490d64665d1a9ff8ee456a3d76. ConciliumId: 1. With 2 TXns and parents 3056f078b3262c643bd1831e06aee95d87b5ada7b2001a284d799487d2634eeb was accepted' ]
2021-04-09T06:56:55.694973756Z [ 'Witness: "172.17.0.2" block "d7a242e4a05075f30c92a78a1e75f6916ce6b4490d64665d1a9ff8ee456a3d76" Round: 4404 commited at Fri Apr 09 2021 06:56:55 GMT+0000 (Coordinated Universal Time) ' ]
2021-04-09T06:57:00.496135850Z [ Error: Block ec008729bca79f3c35c037e13cb782b55e398463cc56af76a2d707bbf4d2ae23 refer to bad parent d7a242e4a05075f30c92a78a1e75f6916ce6b4490d64665d1a9ff8ee456a3d76
2021-04-09T06:57:00.496155180Z       at Witness._canExecuteBlock (/app/node/node.js:1914:27)
2021-04-09T06:57:00.496212282Z       at Witness._processBlock (/app/node/node.js:2105:28)
2021-04-09T06:57:00.496222002Z       at Witness._handleArrivedBlock (/app/node/node.js:444:24) ]
2021-04-09T06:57:00.496662408Z [ 'Incoming message. Peer 54.38.150.125',
2021-04-09T06:57:00.496715983Z   Error: Block ec008729bca79f3c35c037e13cb782b55e398463cc56af76a2d707bbf4d2ae23 refer to bad parent d7a242e4a05075f30c92a78a1e75f6916ce6b4490d64665d1a9ff8ee456a3d76
2021-04-09T06:57:00.496725068Z       at Witness._canExecuteBlock (/app/node/node.js:1914:27)
2021-04-09T06:57:00.496728872Z       at Witness._processBlock (/app/node/node.js:2105:28)
2021-04-09T06:57:00.496732434Z       at Witness._handleArrivedBlock (/app/node/node.js:444:24) ]
2021-04-09T06:57:27.487999000Z [ Error: Block 25034a9b6d1c918c2517449dfb0ed2ca1c1e9f4bbef3ed19549ab5a0531bb668 refer to bad parent ec008729bca79f3c35c037e13cb782b55e398463cc56af76a2d707bbf4d2ae23
2021-04-09T06:57:27.488027272Z       at Witness._canExecuteBlock (/app/node/node.js:1914:27)
2021-04-09T06:57:27.488032467Z       at Witness._processBlockMessage (/app/node/witness.js:321:36) ]

I saved more content of the log [here](https://github.com/fredbellard/anything/blob/main/error%20Bad%20Parent.txt)

Is there something I can do to prevent this issue or to solve it without to recreate the node from scratch?

Let me know if anything
Fred

**Comment by fredbellard** [comment]
Hi again, I forgot to mention: this issue leads to a ban from the network of 24h, which I understand at some point (have to keep the network stable and healthy) but has an important impact on rewards.
thanks!

**Comment by trueshura** [comment]
Thank you for log.
Will fix it next release.
