### ISSUE TITLE
Masternode setup issue - Please help

### ISSUE THREAD

**Issue by HanhTruong** [SilentNotaryEcosystem/Cil-core#33]
I am setting up a masternode per instruction on Ubix Wiki; however I am getting an error when running the nodeStatus.js

Please help.
see the error below - 

============ Error =======================

dayzie@dayzie-masternode:~$ sudo docker exec cil-witness node scripts/nodeStatus.js
[sudo] password for dayzie: 
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:8222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
Emitted 'error' event at:
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by trueshura** [comment]
Show me `sudo docker ps` && `sudo docker logs --tail 100 cil-witness` output
